BASE_PATH:
SITE_PATH: http://www.zwlme.com
qiniu: http://zhuowenli.qiniudn.com

paginate: 30 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
encoding: utf-8
permalink: /:categories/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge

name: 卓文理
title: 卓文理

author:
  name: 卓文理
  email: 531840344@qq.com
  github: zhuowenli
  twitter: vnnlee zhuo
  bio: 我在这里，高清有码！

rss_path: rss.xml

include:      [".htaccess"]
exclude:      ["*.codekit", "*.lock", "Gulpfile.js", "Gemfile", "LICENSE", "node_modules"]
keep_files:   [".git"]
