# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2016

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
    Home: /
    Archives: /archives
    About: /about

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
widget:
    Tags: true
    Categories: false

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
# favicon: Custom your favicon.ico in `site/source`
theme:
    color: Default
    favicon:
        enable: true
        hide_text: (●—●)喔哟，崩溃啦！
        show_text: (/≧▽≦/)咦！又好了！
        icon: /favicon.ico

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
# baidu_analytics:

# Google Analytics
google_analytics: UA-171827500-1

# Disqus
# disqus_shortname:

# Gitalk
# more info please open https://github.com/gitalk/gitalk
gitalk:
    enable: true
    clientID: 3a683f311ce3460b686d
    clientSecret: 264685b8506d937c73b468584847c3b2347bdcfe
    repo: zhuowenli.github.io
    owner: zhuowenli
    admin: zhuowenli
    pagerDirection: first

# ===========================================
# Version
# ===========================================
version: 1.0.0
